theme: jekyll-theme-minimal
title: Welcome to the Zero Trust Network!
description: Feel free to bookmark this to keep an eye on our projects updates.
name: Zero Trust Network, WWU Senior Project
markdown: kramdown
